// installer.go — host dependency installer for provider onboarding.
//
// InstallAll() idempotently brings a bare Linux host to a GPU-ready
// K8s worker: system config (sysctl/modules/resolv.conf) → CNI plugins
// → containerd → kubeadm/kubelet/kubectl → NVIDIA container toolkit →
// containerd NVIDIA runtime. Each step reports progress via
// updateStep so a failed install pinpoints the exact stage.

package sdk

import (
	"context"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"os/exec"
	"strings"
	"time"
)

const (
	// CNIPluginsVersion is the version of CNI plugins to install
	CNIPluginsVersion = "v1.4.0"
	// CNIPluginsURL is the download URL template for CNI plugins
	CNIPluginsURL = "https://github.com/containernetworking/plugins/releases/download/%s/cni-plugins-linux-amd64-%s.tgz"
)

// Installer handles installation of required dependencies.
type Installer struct {
	config   *Config
	progress *InstallProgress
	logger   *slog.Logger
}

// NewInstaller creates a new Installer.
func NewInstaller(config *Config) *Installer {
	logger := slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{
		Level: slog.LevelInfo,
	}))

	return &Installer{
		config: config,
		logger: logger,
		progress: &InstallProgress{
			Steps: []InstallStep{
				{Name: "containerd", Status: "pending"},
				{Name: "kubernetes", Status: "pending"},
				{Name: "nvidia-toolkit", Status: "pending"},
			},
			TotalSteps: 3,
		},
	}
}

// InstallAll installs all required dependencies.
func (i *Installer) InstallAll(ctx context.Context) error {
	i.progress.StartTime = time.Now()

	// Step 1: Install containerd
	if err := i.installContainerd(ctx); err != nil {
		return fmt.Errorf("failed to install containerd: %w", err)
	}

	// Step 2: Install Kubernetes components
	if err := i.installKubernetes(ctx); err != nil {
		return fmt.Errorf("failed to install kubernetes components: %w", err)
	}

	// Step 3: Install NVIDIA Container Toolkit
	if err := i.installNVIDIAToolkit(ctx); err != nil {
		return fmt.Errorf("failed to install nvidia toolkit: %w", err)
	}

	return nil
}

func (i *Installer) updateStep(name, status, message string) {
	for idx := range i.progress.Steps {
		if i.progress.Steps[idx].Name == name {
			i.progress.Steps[idx].Status = status
			i.progress.Steps[idx].Message = message
			if status == "running" {
				i.progress.CurrentStep = idx + 1
			}
			break
		}
	}

	statusIcon := map[string]string{
		"pending": "○",
		"running": "◐",
		"done":    "✓",
		"failed":  "✗",
		"skipped": "○",
	}

	icon := statusIcon[status]
	if icon == "" {
		icon = "○"
	}

	fmt.Printf("  %s %s: %s\n", icon, name, message)
}

// configureSystem configures system prerequisites for Kubernetes.
func (i *Installer) configureSystem(ctx context.Context) error {
	i.updateStep("system-config", "running", "Configuring system...")

	// 1. Ensure resolv.conf exists (required for pod sandbox creation)
	if err := i.ensureResolvConf(); err != nil {
		i.logger.Warn("Failed to configure resolv.conf", "error", err)
	}

	// 2. Disable swap
	if err := i.runCommand(ctx, "swapoff", "-a"); err != nil {
		i.logger.Warn("Failed to disable swap", "error", err)
	}

	// 3. Load required kernel modules
	modules := []string{"overlay", "br_netfilter"}
	for _, mod := range modules {
		if err := i.runCommand(ctx, "modprobe", mod); err != nil {
			i.logger.Warn("Failed to load module", "module", mod, "error", err)
		}
	}

	// 4. Configure kernel modules to load on boot
	modulesConf := "overlay\nbr_netfilter\n"
	if err := os.WriteFile("/etc/modules-load.d/containerd.conf", []byte(modulesConf), 0644); err != nil {
		i.logger.Warn("Failed to write modules config", "error", err)
	}

	// 5. Set sysctl parameters for Kubernetes networking
	sysctlConfig := `net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1`

	if err := os.WriteFile("/etc/sysctl.d/99-kubernetes-cri.conf", []byte(sysctlConfig), 0644); err != nil {
		i.logger.Warn("Failed to write sysctl config", "error", err)
	}

	// Apply sysctl settings
	_ = i.runCommand(ctx, "sysctl", "--system")

	i.updateStep("system-config", "done", "System configured")
	return nil
}

// ensureResolvConf ensures /run/systemd/resolve/resolv.conf exists.
// This is required for containerd to create pod sandboxes.
func (i *Installer) ensureResolvConf() error {
	resolvPath := "/run/systemd/resolve/resolv.conf"

	// Check if file already exists
	if _, err := os.Stat(resolvPath); err == nil {
		return nil
	}

	// Create directory if not exists
	if err := os.MkdirAll("/run/systemd/resolve", 0755); err != nil {
		return fmt.Errorf("failed to create resolve directory: %w", err)
	}

	// Create resolv.conf with Google DNS as fallback
	content := `# Generated by Worldland Provider SDK
nameserver 8.8.8.8
nameserver 8.8.4.4
`
	if err := os.WriteFile(resolvPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write resolv.conf: %w", err)
	}

	i.logger.Info("Created resolv.conf", "path", resolvPath)
	return nil
}

// installCNIPlugins installs CNI plugins required for pod networking.
func (i *Installer) installCNIPlugins(ctx context.Context) error {
	i.updateStep("cni-plugins", "running", "Checking...")

	cniDir := "/opt/cni/bin"
	flannelPath := cniDir + "/flannel"

	// Check if CNI plugins are already installed
	if _, err := os.Stat(flannelPath); err == nil {
		i.updateStep("cni-plugins", "done", "Already installed")
		return nil
	}

	i.updateStep("cni-plugins", "running", "Downloading CNI plugins...")

	// Create CNI directory
	if err := os.MkdirAll(cniDir, 0755); err != nil {
		i.updateStep("cni-plugins", "failed", err.Error())
		return err
	}

	// Download CNI plugins
	url := fmt.Sprintf(CNIPluginsURL, CNIPluginsVersion, CNIPluginsVersion)
	tarPath := "/tmp/cni-plugins.tgz"

	if err := i.downloadFile(ctx, url, tarPath); err != nil {
		i.updateStep("cni-plugins", "failed", "Download failed")
		return fmt.Errorf("failed to download CNI plugins: %w", err)
	}

	i.updateStep("cni-plugins", "running", "Extracting...")

	// Extract to /opt/cni/bin
	if err := i.runCommand(ctx, "tar", "-C", cniDir, "-xzf", tarPath); err != nil {
		i.updateStep("cni-plugins", "failed", "Extraction failed")
		return fmt.Errorf("failed to extract CNI plugins: %w", err)
	}

	// Cleanup
	_ = os.Remove(tarPath)

	i.updateStep("cni-plugins", "done", fmt.Sprintf("Installed (%s)", CNIPluginsVersion))
	return nil
}

// downloadFile downloads a file from URL to the specified path.
func (i *Installer) downloadFile(ctx context.Context, url, filepath string) error {
	// Create HTTP request with context
	req, err := http.NewRequestWithContext(ctx, "GET", url, nil)
	if err != nil {
		return err
	}

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("HTTP error: %d", resp.StatusCode)
	}

	out, err := os.Create(filepath)
	if err != nil {
		return err
	}
	defer out.Close()

	_, err = io.Copy(out, resp.Body)
	return err
}

func (i *Installer) installContainerd(ctx context.Context) error {
	i.updateStep("containerd", "running", "Checking...")

	// Check if containerd is already installed
	if i.isInstalled("containerd") {
		version := i.getVersion("containerd", "--version")
		i.updateStep("containerd", "done", fmt.Sprintf("Already installed (%s)", version))
		return nil
	}

	i.updateStep("containerd", "running", "Installing...")

	// Install containerd
	commands := [][]string{
		{"apt-get", "update"},
		{"apt-get", "install", "-y", "containerd"},
	}

	for _, cmd := range commands {
		if err := i.runCommand(ctx, cmd[0], cmd[1:]...); err != nil {
			i.updateStep("containerd", "failed", err.Error())
			return err
		}
	}

	// Configure containerd for Kubernetes
	if err := i.configureContainerd(ctx); err != nil {
		i.updateStep("containerd", "failed", err.Error())
		return err
	}

	// Start and enable containerd
	if err := i.runCommand(ctx, "systemctl", "enable", "--now", "containerd"); err != nil {
		i.updateStep("containerd", "failed", err.Error())
		return err
	}

	version := i.getVersion("containerd", "--version")
	i.updateStep("containerd", "done", fmt.Sprintf("Installed (%s)", version))
	return nil
}

func (i *Installer) configureContainerd(ctx context.Context) error {
	// Create default config
	if err := os.MkdirAll("/etc/containerd", 0755); err != nil {
		return err
	}

	// Generate default config
	cmd := exec.CommandContext(ctx, "containerd", "config", "default")
	output, err := cmd.Output()
	if err != nil {
		return err
	}

	// Modify config for systemd cgroup
	config := string(output)
	config = strings.ReplaceAll(config, "SystemdCgroup = false", "SystemdCgroup = true")

	return os.WriteFile("/etc/containerd/config.toml", []byte(config), 0644)
}

func (i *Installer) installKubernetes(ctx context.Context) error {
	i.updateStep("kubernetes", "running", "Checking...")

	// Check if kubeadm is already installed
	if i.isInstalled("kubeadm") && i.isInstalled("kubelet") {
		version := i.getVersion("kubeadm", "version", "-o", "short")
		i.updateStep("kubernetes", "done", fmt.Sprintf("Already installed (%s)", version))
		return nil
	}

	i.updateStep("kubernetes", "running", "Installing...")

	// Add Kubernetes apt repository
	commands := [][]string{
		{"apt-get", "update"},
		{"apt-get", "install", "-y", "apt-transport-https", "ca-certificates", "curl", "gpg"},
	}

	for _, cmd := range commands {
		if err := i.runCommand(ctx, cmd[0], cmd[1:]...); err != nil {
			i.updateStep("kubernetes", "failed", err.Error())
			return err
		}
	}

	// Add Kubernetes GPG key
	keyringDir := "/etc/apt/keyrings"
	if err := os.MkdirAll(keyringDir, 0755); err != nil {
		return err
	}

	// Download GPG key to temp file, then dearmor
	keyFile := "/tmp/kubernetes-release.key"
	if err := i.runCommand(ctx, "curl", "-fsSL", "-o", keyFile, "https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key"); err != nil {
		return fmt.Errorf("failed to download kubernetes GPG key: %w", err)
	}

	gpgOutputFile := "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"
	// Remove existing file if any
	_ = os.Remove(gpgOutputFile)

	if err := i.runCommand(ctx, "gpg", "--dearmor", "-o", gpgOutputFile, keyFile); err != nil {
		return fmt.Errorf("failed to add kubernetes GPG key: %w", err)
	}

	// Add apt repository
	repoLine := "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
	if err := os.WriteFile("/etc/apt/sources.list.d/kubernetes.list", []byte(repoLine), 0644); err != nil {
		return err
	}

	// Install kubeadm, kubelet, kubectl
	installCommands := [][]string{
		{"apt-get", "update"},
		{"apt-get", "install", "-y", "kubelet", "kubeadm", "kubectl"},
		{"apt-mark", "hold", "kubelet", "kubeadm", "kubectl"},
	}

	for _, cmd := range installCommands {
		if err := i.runCommand(ctx, cmd[0], cmd[1:]...); err != nil {
			i.updateStep("kubernetes", "failed", err.Error())
			return err
		}
	}

	// Enable kubelet
	if err := i.runCommand(ctx, "systemctl", "enable", "kubelet"); err != nil {
		i.updateStep("kubernetes", "failed", err.Error())
		return err
	}

	version := i.getVersion("kubeadm", "version", "-o", "short")
	i.updateStep("kubernetes", "done", fmt.Sprintf("Installed (%s)", version))
	return nil
}

func (i *Installer) installNVIDIAToolkit(ctx context.Context) error {
	i.updateStep("nvidia-toolkit", "running", "Checking...")

	// Check if nvidia-container-toolkit is already installed
	if i.isInstalled("nvidia-ctk") {
		// Even if installed, ensure containerd is configured
		if err := i.configureNVIDIAContainerd(ctx); err != nil {
			i.logger.Warn("Failed to configure NVIDIA containerd", "error", err)
		}
		i.updateStep("nvidia-toolkit", "done", "Already installed")
		return nil
	}

	i.updateStep("nvidia-toolkit", "running", "Adding repository...")

	// Download GPG key
	gpgKeyPath := "/tmp/nvidia-gpgkey"
	if err := i.runCommand(ctx, "curl", "-fsSL", "https://nvidia.github.io/libnvidia-container/gpgkey", "-o", gpgKeyPath); err != nil {
		i.logger.Warn("Failed to download NVIDIA GPG key", "error", err)
	}

	// Add GPG key
	gpgKeyring := "/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg"
	_ = os.Remove(gpgKeyring) // Remove if exists
	if err := i.runCommand(ctx, "gpg", "--dearmor", "-o", gpgKeyring, gpgKeyPath); err != nil {
		i.logger.Warn("Failed to add NVIDIA GPG key", "error", err)
	}

	// Add repository with correct format
	repoLine := fmt.Sprintf("deb [signed-by=%s] https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /\n", gpgKeyring)
	if err := os.WriteFile("/etc/apt/sources.list.d/nvidia-container-toolkit.list", []byte(repoLine), 0644); err != nil {
		i.logger.Warn("Failed to write NVIDIA repo", "error", err)
	}

	i.updateStep("nvidia-toolkit", "running", "Installing...")

	// Install
	installCommands := [][]string{
		{"apt-get", "update"},
		{"apt-get", "install", "-y", "nvidia-container-toolkit"},
	}

	for _, cmd := range installCommands {
		if err := i.runCommand(ctx, cmd[0], cmd[1:]...); err != nil {
			i.updateStep("nvidia-toolkit", "failed", err.Error())
			return err
		}
	}

	i.updateStep("nvidia-toolkit", "running", "Configuring containerd...")

	// Configure containerd to use NVIDIA runtime
	if err := i.configureNVIDIAContainerd(ctx); err != nil {
		i.logger.Warn("Failed to configure NVIDIA containerd", "error", err)
	}

	i.updateStep("nvidia-toolkit", "done", "Installed and configured")
	return nil
}

// configureNVIDIAContainerd configures containerd to use NVIDIA runtime as default.
func (i *Installer) configureNVIDIAContainerd(ctx context.Context) error {
	// Use nvidia-ctk to configure containerd with --set-as-default
	if err := i.runCommand(ctx, "nvidia-ctk", "runtime", "configure", "--runtime=containerd", "--set-as-default"); err != nil {
		return fmt.Errorf("nvidia-ctk configure failed: %w", err)
	}

	// Check if nvidia config was written to conf.d directory
	nvidiaConfPath := "/etc/containerd/conf.d/99-nvidia.toml"
	mainConfigPath := "/etc/containerd/config.toml"

	if _, err := os.Stat(nvidiaConfPath); err == nil {
		// The nvidia config was written to a separate file
		// We need to ensure the main config imports it
		if err := i.ensureContainerdImports(mainConfigPath); err != nil {
			i.logger.Warn("Failed to configure containerd imports", "error", err)
		}
	}

	// Restart containerd to apply changes
	if err := i.runCommand(ctx, "systemctl", "restart", "containerd"); err != nil {
		return fmt.Errorf("failed to restart containerd: %w", err)
	}

	// Wait for containerd to be ready
	time.Sleep(2 * time.Second)

	// Restart kubelet if running
	_ = i.runCommand(ctx, "systemctl", "restart", "kubelet")

	return nil
}

// ensureContainerdImports ensures the containerd config imports the conf.d directory.
func (i *Installer) ensureContainerdImports(configPath string) error {
	content, err := os.ReadFile(configPath)
	if err != nil {
		return err
	}

	configStr := string(content)

	// Check if imports directive already exists for conf.d
	if strings.Contains(configStr, "/etc/containerd/conf.d/") {
		return nil // Already configured
	}

	// Add imports directive at the beginning
	importsLine := `imports = ["/etc/containerd/conf.d/*.toml"]` + "\n"

	// Prepend imports line
	newConfig := importsLine + configStr

	return os.WriteFile(configPath, []byte(newConfig), 0644)
}

func (i *Installer) getDistribution() string {
	cmd := exec.Command("bash", "-c", ". /etc/os-release && echo $ID$VERSION_ID")
	output, err := cmd.Output()
	if err != nil {
		return "ubuntu22.04"
	}
	return strings.TrimSpace(string(output))
}

func (i *Installer) isInstalled(name string) bool {
	_, err := exec.LookPath(name)
	return err == nil
}

func (i *Installer) getVersion(name string, args ...string) string {
	cmd := exec.Command(name, args...)
	output, err := cmd.Output()
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(strings.Split(string(output), "\n")[0])
}

func (i *Installer) runCommand(ctx context.Context, name string, args ...string) error {
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Stdout = nil // Suppress output unless verbose
	cmd.Stderr = nil

	if i.config.Verbose {
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
	}

	return cmd.Run()
}

// PreflightChecks runs preflight checks for kubeadm.
func (i *Installer) PreflightChecks(ctx context.Context) error {
	// Disable swap
	if err := i.runCommand(ctx, "swapoff", "-a"); err != nil {
		i.logger.Warn("Failed to disable swap", "error", err)
	}

	// Load required kernel modules
	modules := []string{"overlay", "br_netfilter"}
	for _, mod := range modules {
		if err := i.runCommand(ctx, "modprobe", mod); err != nil {
			i.logger.Warn("Failed to load module", "module", mod, "error", err)
		}
	}

	// Set sysctl parameters
	sysctlConfig := `net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1`

	if err := os.WriteFile("/etc/sysctl.d/k8s.conf", []byte(sysctlConfig), 0644); err != nil {
		return err
	}

	return i.runCommand(ctx, "sysctl", "--system")
}
